export default {
  "en": {
    languageName: "English",
    language: "Language",
    addChannel: "Add Channel",
    settings: "Settings",
    feedback: "Send Feedback",
    channels: "Channels",
    feedbackTip: "Thank you for using this application. Share your impression with us!",
    feedbackTemplate: "This application made me feel...",
    close: "Close",
    send: "Send",
    schedule: "Schedule",
    changeSchedule: "Change Schedule",
    mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun",
    monday: "Monday", tuesday: "Tuesday", wednesday: "Wednesday", thursday: "Thursday", friday: "Friday", saturday: "Saturday", sunday: "Sunday",
    step1ChooseDays: "Choose days to publish",
    step2HowManyTimes: "How many times per day",
    step3ChooseDays: "Choose exact time",
    save: "Save",
    cancel: "Cancel",
    pubPerDay: "Publications/Day",
    publishingSchedule: "Publishing Schedule",
    publication: "Publication",
    pasteGDriveLink: "Paste Google Drive Link",
    getFileHint: "Or Drag&Drop video files (MP4, MOV, max 2GB)",
    import: "Import",
    upload: "Upload",
    dropVideos: "Drop videos here to publish them",
    inAQuickWay: "in a quick way",
    videos: "Videos",
    logout: "Log out",
  },
  "ua": {
    languageName: "Українська",
    language: "Мова",
    addChannel: "Додати канал",
    settings: "Налаштування",
    feedback: "Надіслати відгук",
    channels: "Канали",
    feedbackTip: "Дякуємо, що користуєтеся нашим додатком! Поділіться своїми враженнями.",
    feedbackTemplate: "Цей додаток змусив мене відчути...",
    close: "Закрити",
    send: "Надіслати",
    schedule: "Розклад",
    changeSchedule: "Змінити розклад",
    mon: "Пн", tue: "Вт", wed: "Ср", thu: "Чт", fri: "Пт", sat: "Сб", sun: "Нд",
    monday: "Понеділок", tuesday: "Вівторок", wednesday: "Середа", thursday: "Четвер", friday: "П'ятниця", saturday: "Субота", sunday: "Неділя",
    step1ChooseDays: "Оберіть дні для публікації",
    step2HowManyTimes: "Скільки разів на день",
    step3ChooseDays: "Оберіть точний час",
    save: "Зберегти",
    cancel: "Скасувати",
    pubPerDay: "Публікацій/день",
    publishingSchedule: "Розклад публікаций",
    publication: "Публікація",
    pasteGDriveLink: "Вставте посилання на Google Drive",
    getFileHint: "Або перетягніть відеофайли (MP4, MOV, макс. 2ГБ)",
    import: "Імпортувати",
    upload: "Завантажити",
    dropVideos: "Перетягніть відео сюди, щоб опублікувати їх",
    inAQuickWay: "швидким способом",
    videos: "Videos",
    logout: "Log out",
  },
  "ja": {
    languageName: "日本語",
    language: "言語",
    addChannel: "チャンネルを追加",
    settings: "設定",
    feedback: "フィードバックを送信",
    channels: "チャンネル",
    feedbackTip: "アプリをご利用いただきありがとうございます！ご意見をお聞かせください。",
    feedbackTemplate: "このアプリを使って感じたことは...",
    close: "閉じる",
    send: "送信",
    schedule: "スケジュール",
    changeSchedule: "スケジュールを変更",
    mon: "月", tue: "火", wed: "水", thu: "木", fri: "金", sat: "土", sun: "日",
    monday: "月曜日", tuesday: "火曜日", wednesday: "水曜日", thursday: "木曜日", friday: "金曜日", saturday: "土曜日", sunday: "日曜日",
    step1ChooseDays: "投稿する曜日を選択してください",
    step2HowManyTimes: "1日の投稿回数",
    step3ChooseDays: "投稿時間を選択してください",
    save: "保存",
    cancel: "キャンセル",
    pubPerDay: "投稿数/日",
    publishingSchedule: "投稿スケジュール",
    publication: "投稿",
    pasteGDriveLink: "Googleドライブのリンクを貼り付け",
    getFileHint: "またはビデオファイルをドラッグ＆ドロップ（MP4, MOV, 最大2GB）",
    import: "インポート",
    upload: "アップロード",
    dropVideos: "ここに動画をドロップして公開",
    inAQuickWay: "クイックな方法で",
    videos: "Videos",
    logout: "Log out",
  },
}
