export default {
  "en": {
    languageName: "English",
    language: "Language",
    add_channel: "Add Channel",
    settings: "Settings",
    feedback: "Send Feedback",
    channels: "Channels",
    feedback_tip: "Thank you for using this application. Share your impression with us!",
    feedback_template: "This application made me feel...",
    close: "Close",
    send: "Send",
  },
  "ua": {
    languageName: "Українська",
    language: "Мова",
    add_channel: "Додати канал",
    settings: "Налаштування",
    feedback: "Надіслати відгук",
    channels: "Канали",
    feedback_tip: "Thank you for using this application. Share your impression with us!",
    feedback_template: "This application uses made me feel...",
    close: "Close",
    send: "Send",
  },
  "jp": {
    languageName: "日本語",
    language: "言語",
    add_channel: "チャンネルを追加",
    settings: "設定",
    feedback: "フィードバックを送信",
    channels: "チャンネル",
    feedback_tip: "Thank you for using this application. Share your impression with us!",
    feedback_template: "This application uses made me feel...",
    close: "Close",
    send: "Send",
  },
}
